backend:
  name: github
  repo: kristiduckworth/kristiduckworth.github.io
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }